# Resource endpoints that supply the javascript as code that can run in a browser
/dsfunctions:
  get:
    artifact:
      - src/decision-support.js
    engine: resource
    entry: src/decision-support.js
/vc-slider:
  get:
    artifact:
      - src/vc-slider.js
    engine: resource
    entry: src/vc-slider.js

# Service endpoints that take JSON input in a POST request and return a JSON result
/score:
  post:
    artifact:
      - src/decision-support.js
    engine: javascript
    entry: src/decision-support.js
    function: generateScore
/risk:
  post:
    artifact:
      - src/decision-support.js
    engine: javascript
    entry: src/decision-support.js
    function: calculateRisk
/needsAc:
  post:
    artifact:
      - src/decision-support.js
    engine: javascript
    entry: src/decision-support.js
    function: needsAc