/dsfunctions:
  get:
    artifact:
      - src/decision-support.js
    engine: resource
    entry: src/decision-support.js
/vc-slider:
  get:
    artifact:
      - src/vc-slider.js
    engine: resource
    entry: src/vc-slider.js
/score:
  post:
    artifact:
      - src/decision-support.js
    engine: javascript
    entry: src/decision-support.js
    function: generateScore
/risk:
  post:
    artifact:
      - src/decision-support.js
    engine: javascript
    entry: src/decision-support.js
    function: calculateRisk
/needsAc:
  post:
    artifact:
      - src/decision-support.js
    engine: javascript
    entry: src/decision-support.js
    function: needsAc