/dsfunctions:
  get:
    artifact:
      - src/ds.js
    engine: resource
    entry: src/ds.js
/score:
  post:
    artifact:
      - src/ds.js
    engine: javascript
    entry: src/ds.js
    function: generateScore
/risk:
  post:
    artifact:
      - src/ds.js
    engine: javascript
    entry: src/ds.js
    function: calculateRisk
